---
title: "Homework #2"
author: "Lynn Chen"
date: "10/4/2021"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
```


## Problem 1:

Reading and cleaning **Mr. Trash Wheel** sheet.

```{r trashwheel_df}
trashwheel_df = 
  read_xlsx(
    "data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "Mr. Trash Wheel",
    range = cell_cols("A:N")) %>%
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls)
  )
```

Read and clean precipitation data for 2018 and 2019.

```{r 2018 and 2019}
precip_2018 = 
  read_xlsx(
    "data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2018 Precipitation",
    skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(year = 2018) %>% 
  relocate(year)

precip_2019 = 
  read_xlsx(
    "data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2019 Precipitation",
    skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(year = 2019) %>% 
  relocate(year)
```

Combine precipitation datasets. 

```{r combine precip}
precip_df = 
  bind_rows(precip_2018, precip_2019) %>% 
  mutate(month = as.character(month))
```



